### ISSUE TITLE
한 번 돌려봤는데 이런 에러가 발생해서 혹시 내가 잘못 테스트한건지 아님 이슈가 있는건지 확인해줄 수 있을까?? 500이 먼저 뜨긴 했는데 정확히 무엇 때문인지는 모르겠네🤔

### ISSUE THREAD

**Issue by manudeli** [mash-up-kr/muzily-web#37]
한 번 돌려봤는데 이런 에러가 발생해서 혹시 내가 잘못 테스트한건지 아님 이슈가 있는건지 확인해줄 수 있을까?? 500이 먼저 뜨긴 했는데 정확히 무엇 때문인지는 모르겠네🤔
- 시나리오: `/rooms/create` 진입 -> `/login` 으로 리다이렉트 -> 카카오 로그인

<img width="1575" alt="스크린샷 2022-07-14 오후 5 14 31" src="https://user-images.githubusercontent.com/38487811/178935537-477b44b7-41c0-47c2-b8b7-91dfb83a16cb.png">

_Originally posted by @swimjiy in https://github.com/mash-up-kr/Ladder_Web/pull/27#pullrequestreview-1038485493_

**Comment by manudeli** [comment]
> 한 번 돌려봤는데 이런 에러가 발생해서 혹시 내가 잘못 테스트한건지 아님 이슈가 있는건지 확인해줄 수 있을까?? 500이 먼저 뜨긴 했는데 정확히 무엇 때문인지는 모르겠네🤔
> - 시나리오: `/rooms/create` 진입 -> `/login` 으로 리다이렉트 -> 카카오 로그인
> 
> <img width="1575" alt="스크린샷 2022-07-14 오후 5 14 31" src="https://user-images.githubusercontent.com/38487811/178935537-477b44b7-41c0-47c2-b8b7-91dfb83a16cb.png">
> 
> 
> _Originally posted by @swimjiy in https://github.com/mash-up-kr/Ladder_Web/pull/27#pullrequestreview-1038485493_

@swimjiy 체크해보겠습니다!

**Comment by manudeli** [comment]
@swimjiy 지영아 이거 최신 pull 받고 .env.local 업뎃한거지?
나는 다시해봐도 잘 되서 한번 더 확인해주면 좋을 거 같아

쿠키 삭제(localStorage)하고 한 번 더해서 network탭 더 상세히 보여줄 수 있을까??

카카오로그인 버튼 눌러서 카카오에서 인가코드 받으면

END_POINT/auth로 우리 백엔드로 요청하면 백엔드에서 카카오 토큰 받아서 우리한테 필요한 정보 카카오에서 받아오고 우리 서비스 토큰을 프론트로 queryString으로 넘겨주는 방식이거든~ 여기서 문제가 생기는 거 같은데

문제 상황을 좀 더 상세히 보여주면 해결할 수 있을 거 같아~

# 확인해줘야하는 케이스
1. 카카오로그인 안하고 /rooms/create 페이지 방지, /login 페이지 가능
2. 카카오로그인 하고 /rooms/create 페이지 가능, /login 페이지 방지

잘되는 거 확인되면 머지할게

**Comment by swimjiy** [comment]
응 리포팅 했을 당시에도 `.env.local`이랑 작업 파일 버전 모두 최신이었고, 이번엔 `localStorage` 삭제도 해봤는데 바뀌는게 없네ㅠ
카카오 로그인이 되지 않는 상황이라 1번 케이스만 영상 올릴게!

### 에러 시연
https://user-images.githubusercontent.com/38487811/179179906-b9030e41-eac8-4b1a-82b7-970fd489e07b.mov

### 500에러
<img width="595" alt="스크린샷 2022-07-15 오후 5 00 16" src="https://user-images.githubusercontent.com/38487811/179179956-5b972fb7-6838-44cd-930f-871f2ce44406.png">

### 400에러
<img width="595" alt="스크린샷 2022-07-15 오후 5 00 24" src="https://user-images.githubusercontent.com/38487811/179179962-3d3c664e-0ae1-440d-a1cf-8cfffade656a.png">

**Comment by manudeli** [comment]
@swimjiy 지영아 나는 아래 시나리오대로도 잘되네

시나리오: /rooms/create 진입 -> /login 으로 리다이렉트 -> 카카오 로그인

@kor-Chipmunk @Young-mason 선재랑 영권이형도 이거 한 번 체크해줄 수 있어?

**Comment by manudeli** [comment]
> # 확인해줘야하는 케이스
> 1. 카카오로그인 안하고 /rooms/create 페이지 방지, /login 페이지 가능
> 2. 카카오로그인 하고 /rooms/create 페이지 가능, /login 페이지 방지

혹시 브라우저가 whale이라 그런가해서 웨일 설치하고 해봐도 안되네ㅠ
이유를 모르겠솜다...

**Comment by swimjiy** [comment]
저거 확인할 때 크롬도 체크했어서 브라우저 이슈는 아닌듯ㅠ
근데 선재는 된다고 하니까 이건 known issue로 하고 지금 블로킹 되어 있는 PR들 머지한 뒤에 확인해도 괜찮을 것 같아.

**Comment by manudeli** [comment]
> 저거 확인할 때 크롬도 체크했어서 브라우저 이슈는 아닌듯ㅠ 근데 선재는 된다고 하니까 이건 known issue로 하고 지금 블로킹 되어 있는 PR들 머지한 뒤에 확인해도 괜찮을 것 같아.

오키! 일단 이 이슈를 남겨놓고 나중에 클로즈하는 걸로 하자

일단 머지했습니다!

체크해줘서 고마워! 덕분에 타이핑이나 불필요한 요청들도 수정해서 더 깊게 볼 수 있었던 거 같으👍

**Comment by manudeli** [comment]
@swimjiy @Young-mason 

cc. @seungh0 

가입시에 정보제공 동의 안해서 그런거 같은데
백엔드에서 email nullable로 처리한 것 같아
한번 더 테스트 해줄 수 있을까?
https://github.com/mash-up-kr/ladder_backend_spring/commit/097deb778e2d8913c01493d7d9cd941fb4c774cf

**Comment by swimjiy** [comment]
@manudeli 
로그인 잘 되는거 확인해서 이슈 닫아도 될 것 같습니다! 이슈 처리하느라 고생했으👏👏
