### ISSUE TITLE
bug: cz-customizable scope custom으로 나오는 문제

### ISSUE THREAD

**Issue by manudeli** [mash-up-kr/muzily-web#73]

**Comment by kor-Chipmunk** [comment]
저만 그런 게 아니었군요,,

**Comment by manudeli** [comment]
> 저만 그런 게 아니었군요,,

@swimjiy @kor-Chipmunk 
cz-customizable 문제 해결해서 PR 날려놨어
의존성 업데이트 하면서 생긴 간단한 문제더라구

## 제시한 Issue, Pull Request
https://github.com/leoforfree/cz-customizable/issues/201
https://github.com/leoforfree/cz-customizable/pull/202

**Comment by kor-Chipmunk** [comment]
@manudeli 멋쟁이십니다!
